// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Next.js reads .env.local first and .env after it, and the guides put your
// connection string in .env.local. The Prisma CLI reads neither on its own,
// so both are loaded here, in that order: `npx prisma migrate deploy` and
// `npm run dev` then talk to the same database.
//
// A variable already set in the shell still wins over both files, because
// dotenv does not overwrite what is there. That is what the production
// migration in docs/deployment.md relies on:
//   DATABASE_URL="...direct..." npx prisma migrate deploy
config({ path: [".env.local", ".env"], quiet: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Prisma 7 reads the seed command from here. The package.json "prisma"
    // key that older versions used is ignored, silently.
    seed: "ts-node prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
